# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of event')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='HPCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('date_of_birth', models.DateTimeField(verbose_name='date of birth')),
            ],
            options={
                'verbose_name': 'Harry Potter Character',
                'verbose_name_plural': 'Harry Potter Characters',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='hp_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.HPCharacter', verbose_name='Harry Potter Character'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('hp_character', 'title')]),
        ),
    ]
