# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='date of event'),
        ),
        migrations.AlterField(
            model_name='hpcharacter',
            name='date_of_birth',
            field=models.DateField(verbose_name='date of birth'),
        ),
    ]
